Bug fix: use "Fixnum" instead of "FixNum"
1.kind_of?(FixNum) returns
```ruby
irb(main):005:0> 1.kind_of?(FixNum)
NameError: uninitialized constant FixNum
	from (irb):5
	from /Users/stevesmith/.rbenv/versions/2.0.0-p481/bin/irb:12:in `<main>'
```

1.kind_of?(Fixnum) returns
```ruby
irb(main):013:0> 1.kind_of?(Fixnum)
=> true
```